version: '3'

services:
    laravel:
        build: ./docker/laravel
        container_name: laravel
        tty: true
    front:
        build: ./docker/front
        container_name: front
        tty: true
