version: '3'
services:
    laravel:
        build: ./docker/laravel
        volumes:
            - ./laravel:/var/www/html
        tty: true
        ports:
            - 11080:8000
        networks:
            - backend
    nginx:
        build: ./docker/nginx
        tty: true
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./laravel/public:/var/www/html/public
            - ./nginx/logs:/var/log/nginx
        ports:
            - 20080:80
        networks:
            - backend
            - api
    mysql:
        build: ./docker/mysql
        env_file: ./docker/mysql/.env
        volumes:
            - ./mysql/data:/var/lib/mysql
        tty: true
        ports:
            - 13306:3306
        networks:
            - backend
    redis_session:
        build: ./docker/redis_session
        volumes:
            - ./redis/session:/data

        networks:
            - backend
    front:
        build: ./docker/front
        volumes:
            - ./front:/usr/src/app
        tty: true
        ports:
            - 3000:3000
        networks:
            - frontend
            - api
        environment:
            - CHOKIDAR_USEPOLLING=true
    mock:
        build: ./docker/mock
        volumes:
            - ./mock:/usr/src/app
        tty: true
        ports:
            - 4000:4000
        networks:
            - frontend
            - api

    spell_checker:
        build: ./docker/spell_checker
        tty: true
        volumes:
            - ./:/usr/src/app

networks:
    backend:
    frontend:
    api:
