version: 2.1

commands:
  pre-docker-compose:
    steps:
      - checkout
      # ci特有の設定が必要になりそうなら、.env.ci的なのを切る
      - run: cp ./docker/mysql/.env.example ./docker/mysql/.env

executors:
  test-executer:
    machine:
      image: circleci/classic:edge

jobs:
  build:
    executor: test-executer
    steps:
      - pre-docker-compose
      - run: docker-compose build
      - run: mkdir -p /tmp/docker
      - run: docker save clapton:latest -o /tmp/docker/image
      - persist_to_workspace:
            root: /tmp/docker
            paths:
                - image

  npm-front:
    executor: test-executer
    steps:
      - pre-docker-compose
      - attach_workspace:
          at: /tmp/docker
      - run: docker load -i /tmp/docker/image
      - run: docker-compose up -d
      - run: docker-compose exec front npm install

  code-style-check:
    executor: test-executer
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "eslint"
          command: \
              docker-compose exec front npm run lint

workflows:
  version: 2
  test:
    jobs:
      - build
      - npm-front:
          requires:
            - build
      - code-style-check:
          requires:
            - npm-front
