version: 2.1

executors:
  test-executer:
    machine:
      image: circleci/classic:edge

jobs:
  build:
    executor: test-executer
    steps:
      - checkout
      - run: cp ./docker/mysql/.env.example ./docker/mysql/.env
      - run: docker-compose build
      - run: docker-compose up -d

  npm-front:
    executor: test-executer
    steps:
      - run: docker-compose exec front npm install

  code-style-check:
    executor: test-executer
    steps:
      - run:
          name: "eslint"
          command: \
              docker-compose exec front npm run lint

workflows:
  version: 2
  test:
    jobs:
      - build
      - npm-front:
          requires:
            - build
      - code-style-check:
          requires:
            - npm-front
