version: 2.1

executors:
  test-executer:
    machine:
      image: circleci/classic:edge

jobs:
  build:
    executor: test-executer
    steps:
      - checkout
      # ci特有の設定が必要になりそうなら、.env.ci的なのを切る
      - run: cp ./docker/mysql/.env.example ./docker/mysql/.env
      - run: docker-compose build
      - run: docker-compose up -d
      - persist_to_workspace:
          root: .
          paths:
            - .

  npm-front:
    executor: test-executer
    steps:
      - attach_workspace:
          at: .
      - run: docker-compose exec front npm install
      - persist_to_workspace:
          root: .
          paths:
            - .

  code-style-check:
    executor: test-executer
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "eslint"
          command: \
              docker-compose exec front npm run lint

workflows:
  version: 2
  test:
    jobs:
      - build
      - npm-front:
          requires:
            - build
      - code-style-check:
          requires:
            - npm-front
