version: 2.1

commands:
  pre-docker-compose:
    steps:
      - checkout
      # ci特有の設定が必要になりそうなら、.env.ci的なのを切る
      - run: cp ./docker/mysql/.env.example ./docker/mysql/.env

  restore-docker-images:
    steps:
      - restore_cache:
          key: docker-{{ .Revision }}

  restore-front-node_modules:
    steps:
      - restore_cache:
          key: front-node_modules-{{ checksum "./front/package-lock.json" }}

  restore-mock-node_modules:
    steps:
      - restore_cache:
          key: mock-node_modules-{{ checksum "./mock/package-lock.json" }}

  up-docker-compose:
    steps:
      - pre-docker-compose
      - restore-docker-images
      - run: docker load -i /tmp/docker/image
      - run: docker-compose up -d

executors:
  test-executer:
    machine:
      image: circleci/classic:edge

jobs:
  build:
    executor: test-executer
    steps:
      - pre-docker-compose
      - run: docker-compose build
      - run: mkdir -p /tmp/docker
      - run: docker save $(docker images -q) -o /tmp/docker/image
      - save_cache:
            key: docker-{{ .Revision }}
            paths:
                - /tmp/docker/image

  npm-front:
    executor: test-executer
    steps:
      - up-docker-compose
      - run: docker-compose exec front npm install
      - save_cache:
            key: front-node_modules-{{ checksum "./front/package-lock.json" }}
            paths:
                - ./front/node_modules

  npm-mock:
    executor: test-executer
    steps:
      - up-docker-compose
      - run: docker-compose exec mock npm install
      - save_cache:
            key: mock-node_modules-{{ checksum "./mock/package-lock.json" }}
            paths:
                - ./mock/node_modules

  composer-install:
    executor: test-executer
    steps:
      - up-docker-compose
      - run: docker-compose exec mock npm install
      - save_cache:
            key: mock-node_modules-{{ checksum "./mock/package-lock.json" }}
            paths:
                - ./mock/node_modules

  code-style-check:
    executor: test-executer
    steps:
      - up-docker-compose
      - restore-front-node_modules
      - run:
          name: "eslint"
          command: \
              docker-compose exec front npm run lint

workflows:
  version: 2
  test:
    jobs:
      - build
      - npm-front:
          requires:
            - build
      - npm-mock:
          requires:
            - build
      - composer-install:
          requires:
            - build
      - code-style-check:
          requires:
            - npm-front
