query CirclePlacementInEventQuery($circleId: ID!, $eventId: ID!) {
  circlePlacementInEvent(circle_id: $circleId, event_id: $eventId) {
    id
    event_date_id
    hole
    line
    number
    a_or_b
    formatted_placement
    circle_placement_classification_id
    circle {
      id
      name
      kana
    }
    circleProducts {
      id
      name
      price
      circle_product_classification_id
      circleProductClassification {
        id
        name
      }
      wantCircleProducts {
        id
        want_priority_id
        quantity
        careAboutCircle {
          id
          join_event_id
          joinEvent {
            id
            user {
              id
              name
            }
          }
        }
      }
    }
  }
}
