query MeQuery {
  me {
    id
    name
    name_kana
    handle_name
    handle_name_kana
    email
    affiliateTeams {
      team {
        id
        name
      }
    }
    created_at
    updated_at
  }
}
